version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    build:
      context: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./adminer/public:/adminer/public
    environment:
      TZ: Asia/Tokyo
